### ISSUE TITLE
Update Somalomo data

### ISSUE THREAD

**Issue by PPierre22** [gdauby/bdd_plots_central_africa#2]
3 plots à ajouter ? Des remesures ?

**Comment by gdauby** [comment]
Je viens de re-re-re vérifier avec Fernandez, les données de ces 3 nouvelles parcelles Somalomo 12 à 14 sont problématiques : tags totalement incohérents dans les données brutes du Trimble.
De plus, (moins grave) il manque des herbiers.
Bref, il va vérifier.

**Comment by gdauby** [comment]
DONE
